### PR TITLE
Big PR

### LINKED ISSUE #13: Convert ASGS data to use simplified/aligned version of the ontology
https://github.com/CSIRO-enviro-informatics/loci.cat/wiki/Simplifying-the-initial-ontologies describes a simplification of the ASGS datasets to match a more unified Loc-I ontology pattern. The goal is to simplify/harmonize the SPARQL queries. 

The transformations required are illustrated by-example as follows.

Original form:
```
<http://linked.data.gov.au/dataset/asgs2016/meshblock/20663970000>
  rdf:type asgs:MeshBlock ;
  rdf:type geo:Feature ;
  asgs:category "Primary Production" ;
  asgs:mbCode2016 "20663970000" ;
  geox:hasAreaM2 [
      data:value 58387600.000000007450580596923828125 ;
      ns21:crs <http://www.opengis.net/def/crs/EPSG/0/3577> ;
    ] ;
  geox:hasAreaM2 [
      data:value 95157257.606680378 ;
      ns21:crs <http://www.opengis.net/def/crs/EPSG/0/3857> ;
    ] ;
  reg:register <http://linked.data.gov.au/dataset/asgs2016/meshblock/> ;
  geo:hasGeometry [
      rdf:type geo:Geometry ;
      geo:asGML """<gml:MultiSurface ..."""^^geo:gmlLiteral ;
    ] ;
.

<http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/20503108801>
  rdf:type asgs:StatisticalAreaLevel1 ;
  rdf:type geo:Feature ;
  asgs:isStatisticalAreaLevel1Of <http://linked.data.gov.au/dataset/asgs2016/meshblock/20663970000> ;
  asgs:sa1Maincode2016 "20503108801" ;
  asgs:statisticalArea1Sa111DigitCode "20503108801" ;
.
```

Preferred form
1. `asgs:category` → `dcterms:type` whose object is a URI denoting a concept
2. `asgs:mbCode2016` etc → `dcterms:identifier` with a specific literal datatype
3. `asgs:isStatisticalAreaLevel1Of` etc → `geo:sfContains` and add matching `geo:sfWithin` for the inverse case
4. `reg:register` → `loci:isMemberOf` and inverse
5. type of geometry is explicit _or_ geometry is externalized
```
<http://linked.data.gov.au/dataset/asgs2016/meshblock/20663970000>
  rdf:type asgs:MeshBlock ;
  rdf:type asgs:Feature ;
  rdf:type geo:Feature ;
  geox:hasAreaM2 [
      data:value 58387600.000000007450580596923828125 ;
      qb4st:crs <http://www.opengis.net/def/crs/EPSG/0/3577> ;
    ] ;
  geox:hasAreaM2 [
      data:value 95157257.606680378 ;
      qb4st:crs <http://www.opengis.net/def/crs/EPSG/0/3857> ;
    ] ;
  loci:isMemberOf <http://linked.data.gov.au/dataset/asgs2016/meshblock/> ;
  dcterms:identifier "20663970000"^^asgs-id:mbCode2016 ;
  dcterms:type asgs-cat:primary-production ;
  geo:hasGeometry [
      rdf:type sf:MultiSurface ;
      geo:asGML """<gml:MultiSurface ..."""^^geo:gmlLiteral ;
    ] ;
  geo:hasGeometry <http://gds.loci.cat/geometry/asgs16_mb/20663970000> ;
  geo:sfWithin <http://linked.data.gov.au/dataset/asgs2016/stateorterritory/2> ;
  geo:sfWithin <http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/20503108801> ;
.

<http://linked.data.gov.au/dataset/asgs2016/meshblock/>  a loci:Dataset , a rdf:Bag ; 
    rdfs:member <http://linked.data.gov.au/dataset/asgs2016/meshblock/20663970000> .

<http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/20503108801>
  a asgs:Feature ;
  a asgs:StatisticalAreaLevel1 ;
  a geo:Feature ;
  loci:isMemberOf <http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/> ;
  dcterms:identifier "20503108801"^^asgs-id:sa1Maincode2016 ;
  dcterms:identifier "20503108801"^^asgs-id:statisticalArea1Sa111DigitCode ;
  geo:hasGeometry <http://gds.loci.cat/geometry/asgs16_sa1/20503108801> ;
  geo:sfContains <http://linked.data.gov.au/dataset/asgs2016/meshblock/20663970000> ;
  geo:sfWithin <http://linked.data.gov.au/dataset/asgs2016/stateorterritory/2> ;
  geo:sfWithin <http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel2/205031088> ;
.

<http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/>  a loci:Dataset , a rdf:Bag ; 
    rdfs:member <http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/20503108801> .
```

### PR DESCRIPTION
**Pull request by ashleysommer**
Fixes #13

### CODE REVIEW

**Comment by ashleysommer** [comment]
Pushed a massive new commit to this PR.

**Comment by jyucsiro** [comment]
Hi @ashleysommer - checking out this PR on https://pr014.aws.ashs.dev/

Looks promising. I noticed that I wasn't able to view the alternates view via link at the bottom of the feature landing page, e.g. 

https://pr014.aws.ashs.dev/object?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgs2016%2Fsignificanturbanarea%2F1018

links off to -->   https://localhost/object?uri=http://linked.data.gov.au/dataset/asgs2016/meshblock/50215210000&_view=alternates

However, the alternates view page works, e.g. 
https://pr014.aws.ashs.dev/object?uri=http://linked.data.gov.au/dataset/asgs2016/significanturbanarea/1018&_view=alternates

And so does the other views...

Is this simply a config thing on that page?

Otherwise, the `loci` view looks good 
https://pr014.aws.ashs.dev/object?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgs2016%2Fsignificanturbanarea%2F1018&_view=loci&_format=text%2Fturtle

I see you have retained the `asgs` view also, which is cool.

I see you have implemented these ABS features, which are great!:
* SUA
* GCCSA
* RA
* ILOC
* IARE
* IREG
* UCL
* SOSR
* SOS

Also, in reviewing this, I can see the ILOC appearing from the SA1 feature, e.g. https://pr014.aws.ashs.dev/object?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgs2016%2Fstatisticalarealevel1%2F12302144430
(which again is great!)
... and SA4 -> GCCSA

Is this PR going to include these mappings also or in another PR?
* SA1 -> RA
* SA1 -> UCL
* SA2 -> SUA

**Comment by ashleysommer** [comment]
Hi Jonathan,
The issue with localhost appearing in the alternates_view urls is caused by the dyamic-autodeploy reverse-proxy. Thats fixed now.

BTW, I've modified the way the dynamic-autodeployer does its naming. This PR is now deployed here: https://asgs-dataset-pr014.aws.ashs.dev/ 

The SA1->ILOC link and the SA4->GCCSA relationships were easy to implement, because as discussed the link data is present and valid in the WFS endpoint.

In order to get the SA1->RA, SA1->UCL, and SA2->SUA relationships exposed, I will need to finish writing the tooling to extract the links from those ASGS CSV files we downloaded. That will hopefully be done by the tomorrow.

I will do those as a separate PR. This one is big enough.
I'll go ahead and merge this if you think its complete in its current state.

**Review by jyucsiro — APPROVED** [review]
Ok in that case, all good to go with this one

**Pull request merged**
