### PR TITLE
Add new local-lookup relationship links from CSV files

### LINKED ISSUE #16: Some of the new ASGS Features are missing hierarchical relationships
These links _**are**_ present in the underlying ASGS WFS Data Tables

* SA1 to ILOC
  * `SA1.ILOC_CODE_2016 -> ILOC.ILOC_CODE_2016`
* SA4 to GCCSA
  * `SA4.CGGSA_CODE_2016 -> GCCSA.GCCSA_CODE_2016`

So we _do_ have links from existing main-line ASGS features to two of the new features...

And some relationships exist in the WFS properties table, but _**are always null**_:
* SA1 to RA is always null
  * `SA1.RA_CODE_2016 == NULL  -!-> RA.RA_CODE_2016`
* SA1 to UCL is always null
  * `SA1.UCL_CODE_2016 == NULL  -!-> UCL.UCL_CODE_2016`
* SA2 to SUA is always null
  * `SA2.SUA_CODE_2016 == NULL  -!-> SUA.SUA_CODE_2016`

And these hierarchical relationships _**are missing**_:
* ILOC to IARE doesn't exist
  * No way of knowing which IARE an ILOC is within
* IARE to IREG doesn't exist
  * No way of knowing which IREG an IARE is within
* UCL to SOSR doesn't exist
  * No way of knowing which SOSR an UCL is within
* SOSR to SOS doesn't exist
  * No way of knowing which SOS a SOSR is within

Theres a chance there are some kind of joining-tables or node-networks represented on an ABS WFS endpoint that I don't know about, but the main ASGS Feature WFS endpoints don't contain these relationships.

### PR DESCRIPTION
**Pull request by ashleysommer**
Add new relationship links in local lookup tables
A new modified WFS to Geojson mapper which can take into account the new local lookup maps
A new modified WFS to RDF Triples mapper which can take into account the new local lookup maps
Consolidated the two different ASGS WFS to RDF converters into one multi-purpose one.
Added the lookup generator script too

Partially Fixes #16

### CODE REVIEW

**Comment by ashleysommer** [comment]
This PR adds relationships for:
SA1->ILOC
SA1->RA
SA1->UCL
SA2->SUA

Still missing are:
ILOC->IARE
IARE->IREG
UCL->SOSR
SOSR->SOS

Still deciding whether we want to make new local lookup tables for them, or extract their relationship based on the pattern in their identification code.

**Comment by ashleysommer** [comment]
See this auto-deployed here: https://asgs-dataset-pr017.aws.ashs.dev/

**Comment by ashleysommer** [comment]
Added more changes to this pr:

Add derived relationships:
ILOC->IARE
IARE->IREG
UCL->SOSR
SOSR->SOS
including their HTML representation and RDF representation

Accept that some features don't have albers_areas and work around it
(Some RA's have no albers_area, all ILOC, IARE, IREG, UCL, SOSR, SOS, don't have albers_area).
Allow a feature request to return multiple features, and combine them
(Specifically GCCSA "6RTAS", it returns two different WFS features, they need to be combined including summing their Shape_area, albers_area, and Shape_length, and combining their geometry).
Fix some bugs where feature properties are not found
Some optimisations on the util.js javascript file
Removed all of the large .xml files in the /test/ directory and replaced them with .xml.gz files which are approx 1/5th the size.
Added new xml.gz files for the new large features like GCCSAs,

Redeployed here:
https://asgs-dataset-pr017.aws.ashs.dev
(If you have problems with the map on the HTML page not loading, and see a JS error in the web console, you need to ctrl+f5 to force-refresh the page to bring the new util.js file)

**Comment by dr-shorthair** [comment]
Note that the RDF and documentation for the revised asgs ontology are now accessible from 
http://linked.data.gov.au/def/asgs

**Review by jyucsiro — APPROVED** [review]
Looks good. Confirming that SA1 features have relationships to other geographies higher up in the ABS geography hierarchy (ILOC, UCL, RA) and that ILOC, UCL, RAs have respective higher up geographies encoded also. SA2 features also link to SUA regions. That covers all of the ASGS 2016 ABS defined features.

**Comment by ashleysommer** [comment]
Merging.

**Comment by ashleysommer** [comment]
I'll pull all of these changes to the deployed version at asgsld.net

**Comment by jyucsiro** [comment]
cool thanks. i'll work on getting the geometries loaded in the gds

**Pull request merged**
