### PR TITLE
Non abs features

### PR DESCRIPTION
**Pull request by ashleysommer**
Add non-abs asgs features
Also add hasGeometry links to geometry service (missing in previous PR)
also change qb4st:crs to geox:inCRS

### CODE REVIEW

**Comment by ashleysommer** [comment]
Auto-deployed here: https://asgs-dataset-pr019.aws.ashs.dev/

**Comment by jyucsiro** [comment]
Hi @ashleysommer - good work on getting the CED, LGA, NRMR, SSC features into this LD dataset. I'd like to suggest in the HTML view of the features, that we add "ASGS 2016" to the titles of the features.

e.g. for https://asgs-dataset-pr019.aws.ashs.dev/object?uri=http%3A%2F%2Flinked.data.gov.au%2Fdataset%2Fasgs2016%2Flocalgovernmentarea%2F11250

... in the header it has
"Local Government Area
LGA Feature 11250"

It might be misleading just reading the HTML header text that this is the _actual_ LGA, when this is the ABS's approximation of an LGA aligned with MBs. Similarly for the other non-ABS features... does that make sense?

**Comment by ashleysommer** [comment]
@jyucsiro Added the extra text you requested

**Review by jyucsiro — APPROVED** [review]

**Comment by jyucsiro** [comment]
thanks @ashleysommer !

**Pull request merged**
